name: nmr
channels:
  - rdkit
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - numpy=1.19.2
  - openbabel=3.1.1
  - pandas=1.1.3
  - python=3.7.9
  - pip=20.2.4
  - rdkit=2020.09.1.0
  - xtb=6.3.3
  - sqlalchemy=1.3.19
  - psycopg2=1.3.19
  - pip:
    - cclib==1.6.4
    - pyparsing==2.4.7
    - scipy==1.5.3
